services:
  postgres:
    image: postgres:15
    container_name: winwin_postgres
    restart: always
    environment:
      POSTGRES_DB: winwin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-api:
    build:
      context: ./auth-api
    container_name: auth-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/winwin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: vzyKqROxhBglP8jQf/oFBz9YSuzZb+VV++ZrxMzJc/k=
      DATAAPI_URL: http://data-api:8081/api/transform
      INTERNAL_TOKEN: myinternaltoken
    depends_on:
      - postgres
      - data-api

  data-api:
    build:
      context: ./data-api
    container_name: data-api
    restart: always
    ports:
      - "8081:8081"
    environment:
      INTERNAL_TOKEN: myinternaltoken

volumes:
  pgdata:




